using System.CodeDom.Compiler;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HKW.HKWReactiveUI.SourceGenerator;

internal class ClassSourceWriter
{
    public static void Execute(ClassInfo classInfo)
    {
        var w = new ClassSourceWriter(classInfo);
        w.Write();
    }

    public static string FirstClassFullName { get; set; } = string.Empty;

    private readonly ClassInfo _classInfo;
    private readonly IndentedTextWriter _writer;

    public ClassSourceWriter(ClassInfo classInfo)
    {
        _classInfo = classInfo;
        var stringStream = new StringWriter();
        _writer = new IndentedTextWriter(stringStream);
    }

    private void Write()
    {
        _writer.WriteLine("// <auto-generated>");
        _writer.WriteLine("#nullable enable");
        _writer.WriteLine("#pragma warning disable CS1591");
        // 添加全部引用
        _writer.WriteLine(_classInfo.Usings);
        // 手动添加ReactiveUI引用
        if (_classInfo.Usings.All(x => x.ToString() != "using ReactiveUI;"))
            _writer.WriteLine("using ReactiveUI;");
        // 添加命名空间
        _writer.WriteLine($"namespace {_classInfo.Namespace}");
        _writer.WriteLine("{");
        _writer.Indent++;
        // 检测是否为抽象类
        // 获取可访问性
        var accessibility = _classInfo.DeclarationSyntax.Modifiers.GetAccessibility();
        _writer.WriteLine(
            $"{accessibility}{(_classInfo.ClassSymbol.IsAbstract ? " abstract" : string.Empty)} partial class {_classInfo.TypeName}"
        );
        // 添加约束列表
        if (_classInfo.DeclarationSyntax.ConstraintClauses.Count > 0)
            _writer.WriteLine($"{_classInfo.DeclarationSyntax.ConstraintClauses}");
        _writer.WriteLine("{");
        _writer.Indent++;

        foreach (var info in _classInfo.Members)
            _writer.WriteInfo(info);
        GenerateReactiveHelper();

        _writer.Indent--;
        _writer.WriteLine();
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");

        GeneratorHelper.ProductionContext.AddSource(
            $"{_classInfo.FullTypeName.ReplaceBraces()}.ReactiveUI.g.cs",
            ((StringWriter)_writer.InnerWriter).ToString()
        );
    }

    public void GenerateReactiveHelper()
    {
        _writer.WriteLine();
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        _writer.WriteLine($"protected sealed partial class {_classInfo.HelperObjectName}");
        _writer.WriteLine("{");
        _writer.Indent++;
        GenerateReactiveHelperCtor();
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        _writer.WriteLine(GeneratorHelper.DebuggerBrowsableNeverAttribute);
        _writer.WriteLine($"{_classInfo.FullTypeName} _source;");
        foreach (var info in _classInfo.HelperMembers)
            _writer.WriteInfo(info);

        _writer.Indent--;
        _writer.WriteLine("}");
    }

    private void GenerateReactiveHelperCtor()
    {
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);

        _writer.WriteLine(
            $"public {_classInfo.HelperObjectName}({_classInfo.FullTypeName} source)"
        );
        _writer.WriteLine("{");
        _writer.Indent++;
        _writer.WriteLine("_source = source;");

        foreach (var member in _classInfo.InitializeMembers)
        {
            _writer.WriteLine(member);
        }

        _writer.Indent--;
        _writer.WriteLine("}");
    }
}
