using System.CodeDom.Compiler;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HKW.HKWReactiveUI.SourceGenerator;

internal class ClassSourceWriter
{
    public static void Execute(ClassGenerateInfo generateInfo)
    {
        var w = new ClassSourceWriter(generateInfo);
        w.Write();
    }

    public static string FirstClassFullName { get; set; } = string.Empty;

    private readonly ClassGenerateInfo _generatorInfo;
    private readonly IndentedTextWriter _writer;

    public ClassSourceWriter(ClassGenerateInfo generatorInfo)
    {
        _generatorInfo = generatorInfo;
        var stringStream = new StringWriter();
        _writer = new IndentedTextWriter(stringStream);
    }

    private void Write()
    {
        _writer.WriteLine("// <auto-generated>");
        _writer.WriteLine("#nullable enable");
        _writer.WriteLine("#pragma warning disable CS1591");
        // 添加全部引用
        _writer.WriteLine(_generatorInfo.Usings);
        // 手动添加ReactiveUI引用
        if (_generatorInfo.Usings.All(x => x.ToString() != "using ReactiveUI;"))
            _writer.WriteLine("using ReactiveUI;");
        // 添加命名空间
        _writer.WriteLine($"namespace {_generatorInfo.Namespace}");
        _writer.WriteLine("{");
        _writer.Indent++;
        //if (_generatorInfo.FullTypeName == FirstClassFullName)
        //{
        //    // 添加ReferenceType特性,并引用ReactiveObject
        //    // 防止编译器优化,如果整个项目中不引用ReactiveUI,则ReactiveUI的Assembly不会被程序集引用,会导致Fody无法正常构建
        //    _writer.WriteLine("[HKW.HKWReactiveUI.ReferenceType(typeof(ReactiveObject))]");
        //}
        // 检测是否为抽象类
        var isAbstract = _generatorInfo.DeclarationSyntax.Modifiers.Any(SyntaxKind.AbstractKeyword);
        // 获取可访问性
        var accessibility = _generatorInfo.DeclarationSyntax.Modifiers.GetAccessibility();
        _writer.WriteLine(
            $"{accessibility}{(isAbstract ? " abstract" : string.Empty)} partial class {_generatorInfo.TypeName}"
        );
        // 添加约束列表
        if (_generatorInfo.DeclarationSyntax.ConstraintClauses.Count > 0)
            _writer.WriteLine($"{_generatorInfo.DeclarationSyntax.ConstraintClauses}");
        _writer.WriteLine("{");
        _writer.Indent++;

        //GenerateInitializeReactiveObject();
        //_writer.WriteLine();
        foreach (var info in _generatorInfo.Members)
            _writer.WriteInfo(info);
        GenerateReactiveHelper();

        _writer.Indent--;
        _writer.WriteLine();
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");

        GeneratorHelper.ProductionContext.AddSource(
            $"{_generatorInfo.FullTypeName.ReplaceBraces()}.ReactiveUI.g.cs",
            ((StringWriter)_writer.InnerWriter).ToString()
        );
    }

    public void GenerateReactiveHelper()
    {
        _writer.WriteLine();
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        _writer.WriteLine($"protected sealed partial class {_generatorInfo.HelperObjectName}");
        _writer.WriteLine("{");
        _writer.Indent++;
        GenerateReactiveHelperCtor();
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        _writer.WriteLine(GeneratorHelper.DebuggerBrowsableNeverAttribute);
        _writer.WriteLine($"{_generatorInfo.FullTypeName} _source;");
        foreach (var info in _generatorInfo.HelperMembers)
            _writer.WriteInfo(info);

        _writer.Indent--;
        _writer.WriteLine("}");
    }

    private void GenerateReactiveHelperCtor()
    {
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);

        _writer.WriteLine(
            $"public {_generatorInfo.HelperObjectName}({_generatorInfo.FullTypeName} source)"
        );
        _writer.WriteLine("{");
        _writer.Indent++;
        _writer.WriteLine("_source = source;");

        foreach (var member in _generatorInfo.InitializeMembers)
        {
            _writer.WriteLine(member);
        }

        _writer.Indent--;
        _writer.WriteLine("}");
    }
}
