using System.CodeDom.Compiler;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HKW.HKWReactiveUI.SourceGenerator;

internal class ClassSourceWriter
{
    public static void Execute(AssemblyInfo assemblyInfo, ClassGenerateInfo generateInfo)
    {
        var t = new ClassSourceWriter()
        {
            _assemblyInfo = assemblyInfo,
            _generatorInfo = generateInfo,
        };
        t.GenerateClass();
    }

    public static string FirstClassFullName { get; set; } = string.Empty;
#pragma warning disable CS8618
    private AssemblyInfo _assemblyInfo;
    private ClassGenerateInfo _generatorInfo;
    private IndentedTextWriter _writer;
#pragma warning restore CS8618
    private void GenerateClass()
    {
        var stringStream = new StringWriter();
        _writer = new IndentedTextWriter(stringStream);

        _writer.WriteLine("// <auto-generated>");
        _writer.WriteLine("#nullable enable");
        _writer.WriteLine("#pragma warning disable CS1591");
        // 添加全部引用
        _writer.WriteLine(_generatorInfo.Usings);
        // 手动添加ReactiveUI引用
        if (_generatorInfo.Usings.All(x => x.ToString() != "using ReactiveUI;"))
            _writer.WriteLine("using ReactiveUI;");
        // 添加命名空间
        _writer.WriteLine($"namespace {_generatorInfo.Namespace}");
        _writer.WriteLine("{");
        _writer.Indent++;
        if (_generatorInfo.FullTypeName == FirstClassFullName)
        {
            // 添加ReferenceType特性,并引用ReactiveObject
            // 防止编译器优化,如果整个项目中不引用ReactiveUI,则ReactiveUI的Assembly不会被程序集引用,会导致Fody无法正常构建
            _writer.WriteLine("[HKW.HKWReactiveUI.ReferenceType(typeof(ReactiveObject))]");
        }
        // 检测是否为抽象类
        var isAbstract = _generatorInfo.DeclarationSyntax.Modifiers.Any(SyntaxKind.AbstractKeyword);
        // 获取可访问性
        var accessibility = _generatorInfo.DeclarationSyntax.Modifiers.GetAccessibility();
        _writer.WriteLine(
            $"{accessibility}{(isAbstract ? " abstract" : string.Empty)} partial class {_generatorInfo.TypeName}"
        );
        // 添加约束列表
        _writer.WriteLine($"{_generatorInfo.DeclarationSyntax.ConstraintClauses}");
        _writer.WriteLine("{");
        _writer.Indent++;

        GenerateInitializeReactiveObject();
        _writer.WriteLine();
        foreach (var info in _generatorInfo.MemberInfos)
            _writer.WriteInfo(info);

        _writer.Indent--;
        _writer.WriteLine();
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");

        _assemblyInfo.ProductionContext.AddSource(
            $"{_generatorInfo.FullTypeName.Replace('<', '{').Replace('>', '}')}.ReactiveUI.g.cs",
            stringStream.ToString()
        );
    }

    private void GenerateInitializeReactiveObject()
    {
        if (_generatorInfo.InitializeMembers.Count is 0)
            return;
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(SourceGeneratorHelper.GeneratedCodeAttribute);

        _writer.WriteLine("protected void InitializeReactiveObject()");
        _writer.WriteLine("{");
        _writer.Indent++;

        foreach (var member in _generatorInfo.InitializeMembers)
        {
            _writer.WriteLine(member);
        }

        _writer.Indent--;
        _writer.WriteLine("}");
    }
}
